version: '3.8'
services:
  quietspace-frontend:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    image: thural/quietspace:frontend
    container_name: quietspace_frontend_container
    ports:
      - "5000:80"