version: '3.8'
services:
  quietspace-frontend:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    image: thural/quietspace:frontend-dev
    container_name: quietspace_frontend_container
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /node_modules