name: BSN Frontend Pipeline

on:
  push:
    branches:
      - ["main", "prod"]
    paths:
      - docker/prod/**
      - 'docker-compose.yaml'
      - .github/workflows/*-frontend.yml
jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract project version
        id: extract_version
        run: |
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: docker/prod/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quietspace:frontend-latest,${{ secrets.DOCKERHUB_USERNAME }}/quietspace:frontend-${{ steps.extract_version.outputs.VERSION }}

  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-22.04
    needs: [ build-image ]
    steps:

      - name: Create deployment folder
        run: ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p deployment"

      - name: Copy docker-compose file
        run: scp -oStrictHostKeyChecking=no docker-compose.yaml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:deployment/docker-compose.yaml

      - name: Set ENV variable and deploy
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          cd deployment
          docker compose -f docker-compose.yaml pull -q
          docker compose -f docker-compose.yaml up -d
          EOF